/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\Hall_Building.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hall_Building.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2011.geometry} material={materials['material.008']} position={[31.448, 2.58, -15.492]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2064.geometry} material={materials['16_Terrazzo_surface_PBR_texture-seamless.002']} position={[27.69, 1.832, -16.412]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2065.geometry} material={materials['Color_008.005']} position={[28.997, 6.272, -15.799]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2070.geometry} material={materials['Color_008.005']} position={[28.998, 6.731, -15.799]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2071.geometry} material={materials['Color_008.005']} position={[28.998, 6.792, -15.799]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2083.geometry} material={materials['24_pool_water_texture_seamless.001']} position={[25.195, 1.765, -15.563]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2104.geometry} material={materials.Water_Deep} position={[27.192, 1.665, -15.205]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2111.geometry} material={materials['31_brushed_copper_metal_texture-seamless.003']} position={[30.578, 2.98, -14.929]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2112.geometry} material={materials['31_brushed_copper_metal_texture-seamless.003']} position={[30.643, 3.451, -18.819]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2122.geometry} material={materials['26_old_dirty_copper_metal_texture-seamless.003']} position={[30.586, 3.165, -15.693]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2123.geometry} material={materials['Color_M07.003']} position={[29.888, 7.423, -15.487]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2129.geometry} material={materials['Color_M07.003']} position={[30.436, 7.435, -15.149]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2130.geometry} material={materials['Color_M07.003']} position={[28.897, 7.435, -18.61]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2154.geometry} material={materials.Slate_staggered_yovds6} position={[27.149, 7.611, -15.708]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material3001.geometry} material={materials.Fluted_Granite__Stack_1} position={[30.159, 5.698, -15.798]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2110.geometry} material={materials['31_brushed_copper_metal_texture-seamless.003']} position={[30.597, 2.99, -17.284]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2202.geometry} material={materials['26_old_dirty_copper_metal_texture-seamless.003']} position={[30.586, 2.808, -15.738]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2039.geometry} material={materials['40_black_portoro_gold_pbr_texture-seamless']} position={[32.009, 2.164, -13.404]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2040.geometry} material={materials['Color_008.005']} position={[31.996, 2.236, -13.516]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2041.geometry} material={materials['Color_008.005']} position={[31.946, 2.221, -14.071]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <group position={[31.925, 8.459, -14.302]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021}>
        <mesh geometry={nodes.Material2413.geometry} material={materials['Color_008.005']} />
        <mesh geometry={nodes.Material2413_1.geometry} material={materials.Fluted_Granite__Stack} />
        <mesh geometry={nodes.Material2413_2.geometry} material={materials['material.008']} />
      </group>
      <mesh geometry={nodes.Material2023.geometry} material={materials['Seamless_stucco_plaster_-black']} position={[30.133, 5.795, -15.798]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2021.geometry} material={materials.Fluted_Granite__Stack} position={[29.692, 5.51, -15.662]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2015.geometry} material={materials['material.008']} position={[30.673, 4.824, -16.392]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2067.geometry} material={materials['Color_008.005']} position={[27.395, 7.538, -15.708]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2018.geometry} material={materials['Pale_lancelot_oak_PBR.003']} position={[30.26, 3.759, -15.158]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2017.geometry} material={materials['Pale_lancelot_oak_PBR.003']} position={[30.453, 5.83, -16.798]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2016.geometry} material={materials['material.008']} position={[30.032, 5.99, -15.36]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2075.geometry} material={materials['Polished_Concrete_Old.001']} position={[26.048, 7.007, -15.715]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2024.geometry} material={materials['sehpa_mermer__marble.002']} position={[28.447, 2.401, -15.577]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2063.geometry} material={materials.material_77} position={[28.988, 4.931, -15.769]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2019.geometry} material={materials['Pale_lancelot_oak_PBR.003']} position={[30.597, 4.727, -15.979]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material3018.geometry} material={materials.Pale_lancelot_oak_PBR_10} position={[30.465, 3.095, -15.28]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material3012.geometry} material={materials.Pale_lancelot_oak_PBR_10} position={[30.715, 3.163, -17.64]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2311.geometry} material={materials['Translucent_Glass_Gray.005']} position={[30.447, 5.425, -15.72]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <group position={[30.571, 3.026, -15.719]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021}>
        <mesh geometry={nodes.Material2423.geometry} material={materials['Color_M07.003']} />
        <mesh geometry={nodes.Material2423_1.geometry} material={materials.Pale_lancelot_oak_PBR_10} />
      </group>
      <mesh geometry={nodes.Material2076.geometry} material={materials.Weathered_Timber_Staggered} position={[32.27, 1.79, -17.688]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2201.geometry} material={materials.Charred_Timber} position={[27.882, 4.474, -12.362]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2224.geometry} material={materials.Charred_Timber} position={[27.887, 4.405, -19.223]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2010.geometry} material={materials['material.009']} position={[27.473, 7.456, -15.511]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2103.geometry} material={materials['E27_3D_Emissive_White1.001']} position={[29.09, 6.077, -15.764]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh geometry={nodes.Material2157.geometry} material={materials.FREIXO_PAINEL} position={[29.382, 7.346, -15.66]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
    </group>
  )
}

useGLTF.preload('/Hall_Building.gltf')
