/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/okay/ok.glb -D 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ok.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.OkMesh.geometry} material={materials.ok_material} />
    </group>
  )
}

useGLTF.preload('/ok.glb')
