/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\swimmingPool.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/swimmingPool.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[24.428, 2.096, -9.852]}>
        <mesh geometry={nodes.Material2033.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2033_1.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2033_2.geometry} material={materials['Texture_2.jpeg']} />
        <mesh geometry={nodes.Material2033_3.geometry} material={materials.Translucent_Glass_Gray} />
      </group>
      <group position={[29.845, 2.133, -9.627]}>
        <mesh geometry={nodes.Material2043.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2043_1.geometry} material={materials['1_16']} />
        <mesh geometry={nodes.Material2043_2.geometry} material={materials.Plain_Natural_Blackout} />
      </group>
    </group>
  )
}

useGLTF.preload('/swimmingPool.gltf')
