/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\MasterBedRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MasterBedRoom(props) {
  const { nodes, materials } = useGLTF('./models3/MasterBedRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2249.geometry} material={materials.Plain_Natural_Blackout} position={[15.897, 5.118, -19.559]} />
      <mesh geometry={nodes.Material2211.geometry} material={materials.material} position={[15.961, 4.959, -18.605]} />
      <group position={[15.861, 5.282, -18.741]}>
        <mesh geometry={nodes.Material2463.geometry} material={materials.material_47} />
        <mesh geometry={nodes.Material2463_1.geometry} material={materials.material} />
      </group>
      <mesh geometry={nodes.Material2056.geometry} material={materials.Plain_Natural_Blackout_Sheer} position={[14.802, 5.631, -17.887]} />
      <group position={[15.912, 4.5, -17.825]}>
        <mesh geometry={nodes.Material2462.geometry} material={materials['Camel___Ivory_Rug__Labyrinth__-_Jonathan_Adler']} />
        <mesh geometry={nodes.Material2462_1.geometry} material={materials.Dense_Rattan} />
      </group>
      <mesh geometry={nodes.Material2385.geometry} material={materials.material} position={[19.081, 6.003, -18.191]} />
      <mesh geometry={nodes.Material2209.geometry} material={materials['Andy_Burgess_-_02']} position={[19.079, 6.001, -17.646]} />
      <mesh geometry={nodes.Material2208.geometry} material={materials['Andy_Burgess_-_01']} position={[19.079, 6.001, -18.738]} />
      <mesh geometry={nodes.Material2386.geometry} material={materials.Color_008} position={[19.076, 6.003, -18.191]} />
      <group position={[18.939, 4.757, -18.185]}>
        <mesh geometry={nodes.Material2471.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Material2471_1.geometry} material={materials.material_47} />
        <mesh geometry={nodes.Material2471_2.geometry} material={materials.Charred_Timber_11} />
        <mesh geometry={nodes.Material2471_3.geometry} material={materials.Color_008} />
      </group>
      <group position={[17.798, 5.556, -14.586]}>
        <mesh geometry={nodes.Material2479.geometry} material={materials.Mirror_01} />
        <mesh geometry={nodes.Material2479_1.geometry} material={materials['31_brushed_copper_metal_texture-seamless']} />
      </group>
      <group position={[17.8, 5.026, -14.813]}>
        <mesh geometry={nodes.Material2480.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2480_1.geometry} material={materials['40_black_portoro_gold_pbr_texture-seamless']} />
      </group>
      <group position={[15.732, 6.103, -14.623]}>
        <mesh geometry={nodes.Material2311.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2311_1.geometry} material={materials.Color_F19} />
      </group>
      <group position={[15.713, 5.658, -14.533]}>
        <mesh geometry={nodes.Material2313.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2313_1.geometry} material={materials['Smart-TV-Menu']} />
        <mesh geometry={nodes.Material2313_2.geometry} material={materials.Color_M07} />
        <mesh geometry={nodes.Material2313_3.geometry} material={materials.Translucent_Glass_Gray} />
      </group>
      <mesh geometry={nodes.Material2008.geometry} material={materials.material} position={[17.77, 5.599, -14.579]} />
      <group position={[15.623, 4.76, -14.771]}>
        <mesh geometry={nodes.Material2495.geometry} material={materials.material_47} />
        <mesh geometry={nodes.Material2495_1.geometry} material={materials.Charred_Timber_11} />
        <mesh geometry={nodes.Material2495_2.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Material2495_3.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2495_4.geometry} material={materials.Color_008} />
      </group>
      <group position={[14.38, 6.127, -19.629]}>
        <mesh geometry={nodes.Material2502.geometry} material={materials['26_old_dirty_copper_metal_texture-seamless']} />
        <mesh geometry={nodes.Material2502_1.geometry} material={materials.Translucent_Glass_Gray} />
      </group>
      <group position={[17.4, 6.127, -19.629]}>
        <mesh geometry={nodes.Material2503.geometry} material={materials['26_old_dirty_copper_metal_texture-seamless']} />
        <mesh geometry={nodes.Material2503_1.geometry} material={materials.E27_3D_Emissive_White1} />
      </group>
      <group position={[17.521, 4.846, -15.05]}>
        <mesh geometry={nodes.Material2508.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2508_1.geometry} material={materials.Plain_Natural_Blackout} />
      </group>
      <mesh geometry={nodes.Material2392.geometry} material={materials.material_47} position={[15.732, 6.176, -14.571]} />
      <group position={[15.89, 7.501, -18.641]}>
        <mesh geometry={nodes.Material2514.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2514_1.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Material2514_2.geometry} material={materials.E27_3D_Emissive_White1} />
      </group>
      <mesh geometry={nodes.Material2142.geometry} material={materials.E27_3D_Emissive_White1} position={[14.38, 6.176, -19.606]} />
      <mesh geometry={nodes.Material2373.geometry} material={materials.material} position={[15.896, 6.57, -18.624]} />
      <mesh geometry={nodes.Material2145.geometry} material={materials.Translucent_Glass_Gray} position={[17.4, 6.176, -19.606]} />
    </group>
  )
}

useGLTF.preload('./models3/MasterBedRoom.gltf')
