/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\studyArea.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from "../../constants/Customization";

export function StudyArea(props) {
  const { nodes, materials } = useGLTF('./models3//studyArea.gltf')
	const { codeOBJ, loc, setLoc } = useCustomization();

  return (
    <group {...props} dispose={null}>
      <group position={[20.841, 6.073, -18.661]}>
        <mesh geometry={nodes.Material2364.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2364_1.geometry} material={materials.Color_008} />
      </group>
      <mesh geometry={nodes.Material2282.geometry} material={materials.material} position={[20.761, 4.76, -17.982]} />
      <mesh geometry={nodes.Material2287.geometry} material={materials.material} position={[20.817, 4.744, -17.984]} />
      <group position={[20.693, 4.636, -18.006]}>
        <mesh geometry={nodes.Material2369.geometry} material={materials.Charred_Timber_11} />
        <mesh geometry={nodes.Material2369_1.geometry} material={materials.material_12} />
      </group>
      <mesh geometry={nodes.Material2180.geometry} material={materials.material_15_19} position={[20.682, 6.302, -18.77]} />
      <mesh geometry={nodes.Material2173.geometry} material={materials.material_12} position={[20.686, 4.933, -18.643]} />
      <group position={[20.839, 4.499, -17.622]}>
        <mesh geometry={nodes.Material2378.geometry} material={materials['Camel___Ivory_Rug__Labyrinth__-_Jonathan_Adler']} />
        <mesh geometry={nodes.Material2378_1.geometry} material={materials.Dense_Rattan} />
      </group>
      <mesh geometry={nodes.Material2293.geometry} material={materials.material_12} position={[20.773, 6.308, -18.746]} />
      <mesh geometry={nodes.Material2294.geometry} material={materials.Color_008} position={[21.037, 6.942, -18.625]} />
      <mesh geometry={nodes.Material2296.geometry} material={materials.Concrete_and_Wood_02} position={[19.281, 6.11, -17.583]} />
      <group position={[19.283, 6.111, -17.58]}>
        <mesh geometry={nodes.Material2388.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2388_1.geometry} material={materials.material} />
      </group>
      <group position={[22.891, 4.82, -14.358]} rotation={[0, 0.635, 0]}>
        <mesh geometry={nodes.Material2354.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2354_1.geometry} material={materials.PDM_Leather_BandB_AC_Lounge_2_18} />
        <mesh geometry={nodes.Material2354_2.geometry} material={materials.Oak_2} />
        <mesh geometry={nodes.Material2354_3.geometry} material={materials.material_12} />
      </group>
      <mesh geometry={nodes.Material2163.geometry} material={materials.Pale_lancelot_oak_PBR} position={[24.013, 4.694, -14.594]} />
      <mesh geometry={nodes.Material2273.geometry} material={materials.material} position={[23.865, 4.99, -14.534]} />
      <mesh geometry={nodes.Material2162.geometry} material={materials.zand1} position={[23.974, 4.793, -14.019]} />
      <group position={[23.309, 4.514, -14.613]}>
        <mesh geometry={nodes.Material2350.geometry} material={materials.Persian_Rug_blue} />
        <mesh geometry={nodes.Material2350_1.geometry} material={materials.Dense_Rattan} />
      </group>
      <mesh geometry={nodes.Material2001.geometry} material={materials.Concrete_and_Wood} position={[19.281, 6.11, -14.654]} />
      <group position={[19.283, 6.111, -14.651]}>
        <mesh geometry={nodes.Material2025.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2025_1.geometry} material={materials.material} />
      </group>
      <mesh geometry={nodes.Material2102.geometry} material={materials.material} position={[23.309, 4.511, -14.613]} />
      <group position={[21.485, 4.82, -16.865]} rotation={[0, 1.524, 0]}>
        <mesh geometry={nodes.Material2557.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material2557_1.geometry} material={materials.PDM_Leather_BandB_AC_Lounge_2_18} />
        <mesh geometry={nodes.Material2557_2.geometry} material={materials.Oak_2} />
        <mesh geometry={nodes.Material2557_3.geometry} material={materials.material_12} />
      </group>
      <group position={[21.682, 4.887, -17.987]}>
        <mesh geometry={nodes.mesh065.geometry} material={materials.material_50} />
        <mesh geometry={nodes.mesh065_1.geometry} material={materials.White_Painted_Stone_Tall_Green} />
        <mesh geometry={nodes.mesh065_2.geometry} material={materials['23_brushed_dark_steel_metal']} />
      </group>
      <group position={[22.028, 5.074, -14.193]}>
        <mesh geometry={nodes.mesh059.geometry} material={materials.Color_F19} />
        <mesh geometry={nodes.mesh059_1.geometry} material={materials.material} />
        <mesh geometry={nodes.mesh059_2.geometry} material={materials.Grass} />
      </group>
      <group position={[19.869, 4.854, -17.549]}>
        <mesh geometry={nodes.Material2034.geometry} material={materials.AAAA} />
        <mesh geometry={nodes.Material2034_1.geometry} material={materials.Corduroy_17} />
        <mesh geometry={nodes.Material2034_2.geometry} material={materials.Geometric_Natural_Jacquard} />
      </group>
    </group>
  )
}

useGLTF.preload('./models3//studyArea.gltf')
