/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\Dinning_part2.gltf 
*/

import React, { useRef } from 'react'
import { Loader } from '@react-three/drei'
import { useLoader  } from "@react-three/fiber";
import { useCustomization } from "../../../constants/Customization";
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function Dinning(props) {
	const { codeOBJ, loc, setLoc } = useCustomization();
  const table_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/table_a_obj/d_table_a.glb')
  const sofa_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/sofa_a_obj/d_sofa_a.glb')
  const rug_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/self_a_obj/d_rug_a.glb')
  const self_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/self_a_obj/d_self_a.glb')
  const dinningCommon = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dinningRoom_common/d_commom.glb')
  // const mainBuilding = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/mainBuiling/mainBuilding.glb')
  const mainBuilding = useLoader(GLTFLoader, './public/models/mainBuilding.glb')


  return (
    <>
      <primitive object={mainBuilding.scene} />
      <primitive object={table_a.scene} />
      <primitive object={sofa_a.scene} />
      <primitive object={self_a.scene} />
      <primitive object={rug_a.scene} />
      <primitive object={dinningCommon.scene} />
    </>
  )
}


