/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\Dinning_part2.gltf 
*/

import React, { useRef } from 'react'
import { useLoader  } from "@react-three/fiber";
import { useCustomization } from "../../../constants/Customization";
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function Dinning(props) {
	const { codeOBJ, loc, setLoc } = useCustomization();
  // const dn_table_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_table/dn_table_a.glb')
  // const dn_table_b = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_table/dn_table_b.glb')
  // const dn_clock_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_clock_a_obj/d_clock_a.glb')
  // const dn_clock_b = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_clock_b_obj/d_clock_b.glb')
  // const dn_lamp_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_lamp_a_obj/dn_lamp_a.glb')
  // const dn_lamp_b = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_lamp_b_obj/dn_lamp_b.glb')
  // const dn_lamp_c = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_lamp_c_obj/dn_lamp_c.glb')
  // const dn_lamp_d = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_lamp_d_obj/dn_lamp_d.glb')
  // const dn_lamp_e = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/dn_lamp_e_obj/dn_lamp_e.glb')
 
  return (
    <>
      {/* <primitive object={d_table_a.scene} /> */}
      {/* <primitive object={dn_table_a.scene} />
      <primitive object={dn_table_b.scene} /> */}
      
    </>
  )
}


