/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\Drawing.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../../../constants/Customization";
// import { InteractionUI } from "./InteractionUI";

export function Drawing(props) {
	const { nodes, materials } = useGLTF("./models3/Drawing.gltf");
	const { codeOBJ, loc, setLoc, rug } = useCustomization();

	return (
		<group {...props} dispose={null}>
			<group
				position={[16.84, 1.664, -15.305]}
				visible={codeOBJ["dSofa"] === 1}
			>
				{/* <InteractionUI target="dsofa1"/> */}
				<mesh
					geometry={nodes.mesh011.geometry}
					material={materials.Sofa_Dark}
				/>
				<mesh
					geometry={nodes.mesh011_1.geometry}
					material={materials.Material}
				/>
				<mesh
					geometry={nodes.mesh011_2.geometry}
					material={materials.Sofa_Gray}
				/>
			</group>
			<group
				position={[16.557, 1.632, -15.304]}
				visible={codeOBJ["dSofa"] === 0}
			>
				<mesh
					geometry={nodes.mesh029.geometry}
					material={materials["green-leather_texture-seamless"]}
				/>
				<mesh
					geometry={nodes.mesh029_1.geometry}
					material={materials.White_Painted_Stone_Tall_Green}
				/>
				<mesh
					geometry={nodes.mesh029_2.geometry}
					material={materials.PDM_Leather_BandB_AC_Lounge_2}
				/>
			</group>
			<group position={[16.667, 1.937, -15.441]}>
				<mesh
					geometry={nodes.Material2282.geometry}
					material={materials.material}
				/>
				<mesh
					geometry={nodes.Material2282_1.geometry}
					material={materials.Color_F19}
				/>
				<mesh
					geometry={nodes.Material2282_2.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2282_3.geometry}
					material={materials.Color_D02}
				/>
			</group>
			<mesh
				geometry={nodes["D-Self-main001"].geometry}
				material={materials.Pale_lancelot_oak_PBR}
				position={[15.2, 2.301, -18.08]}
			/>
			<mesh
				geometry={nodes.Material2028.geometry}
				material={materials["Smart-TV-Menu"]}
				position={[14.071, 2.36, -16.593]}
			/>
			<mesh
				geometry={nodes.Material2033.geometry}
				material={materials.material}
				position={[13.934, 1.909, -16.328]}
			/>
			<mesh
				geometry={nodes.Material2043.geometry}
				material={materials.Vegetation_Bark_Maple2}
				position={[13.642, 2.233, -14.64]}
			/>
			<mesh
				geometry={nodes.Material2044.geometry}
				material={materials.material_6}
				position={[13.644, 2.233, -14.644]}
			/>
			<mesh
				geometry={nodes.Material2029.geometry}
				material={materials.Color_008}
				position={[13.922, 2.172, -15.343]}
			/>
			<group position={[16.667, 1.937, -15.441]}>
				<mesh
					geometry={nodes.Material2255.geometry}
					material={materials.material}
				/>
				<mesh
					geometry={nodes.Material2255_1.geometry}
					material={materials.Color_F19}
				/>
				<mesh
					geometry={nodes.Material2255_2.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2255_3.geometry}
					material={materials.Color_D02}
				/>
			</group>
			<mesh
				geometry={nodes.Material2124.geometry}
				material={materials.Color_M07}
				position={[14.069, 2.36, -16.594]}
			/>
			<mesh
				geometry={nodes.Material2025.geometry}
				material={materials.Translucent_Glass_Gray}
				position={[14.069, 2.36, -16.594]}
			/>
			<group position={[16.819, 4.042, -15.469]}>
				<mesh
					geometry={nodes.Material2432.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2432_1.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2432_2.geometry}
					material={materials.E27_3D_Emissive_White1}
				/>
			</group>
			<group position={[19.02, 2.058, -14.873]}>
				<mesh
					geometry={nodes.Material2262.geometry}
					material={materials.Pale_lancelot_oak_PBR}
				/>
				<mesh
					geometry={nodes.Material2262_1.geometry}
					material={materials.Color_008}
				/>
				<mesh
					geometry={nodes.Material2262_2.geometry}
					material={
						materials["26_old_dirty_copper_metal_texture-seamless"]
					}
				/>
				<mesh
					geometry={nodes.Material2262_3.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2262_4.geometry}
					material={materials.material}
				/>
				<mesh
					geometry={nodes.Material2262_5.geometry}
					material={materials["24_pool_water_texture_seamless"]}
				/>
			</group>
			<mesh
				geometry={nodes.Material2379.geometry}
				material={materials.Translucent_Glass_Gray}
				position={[16.82, 3.901, -15.47]}
			/>
			<mesh
				geometry={nodes.Material2437.geometry}
				material={materials.Color_M07}
				position={[16.82, 4.124, -15.47]}
			/>
			<mesh
				geometry={nodes.Retopo_Material2136.geometry}
				material={materials["vase-ode-to-baydo"]}
				position={[14.058, 2.321, -17.836]}
			/>
			<mesh
				geometry={nodes["D-centerTable-B"].geometry}
				material={materials["Material.005"]}
				position={[16.873, 1.472, -15.301]}
				visible={codeOBJ["dTable"] === 1}
			/>
			<group
				position={[16.926, 1.486, -15.312]}
				visible={codeOBJ["dTable"] === 0}
			>
				<mesh
					geometry={nodes.Material2248.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2248_1.geometry}
					material={materials.Pale_lancelot_oak_PBR}
				/>
			</group>
			<mesh
				geometry={nodes["D-Rug-B"].geometry}
				material={
					rug === "black"
						? materials.Sofa_Dark
						: materials[
								"Camel___Ivory_Rug__Labyrinth__-_Jonathan_Adler"
						  ]
				}
				position={[16.872, 1.371, -15.33]}
			/>
			<group position={[16.586, 1.338, -15.547]}>
				<mesh
					geometry={nodes.Material2273.geometry}
					material={
						materials[
							"Camel___Ivory_Rug__Labyrinth__-_Jonathan_Adler"
						]
					}
				/>
				<mesh
					geometry={nodes.Material2273_1.geometry}
					material={materials.Dense_Rattan}
				/>
			</group>
			<mesh
				geometry={nodes["D-Self-B"].geometry}
				material={materials.material_18}
				position={[15.188, 1.956, -18.077]}
			/>
			<group position={[15.19, 1.999, -18.101]}>
				<mesh
					geometry={nodes.Material2218.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2218_1.geometry}
					material={materials.Pale_lancelot_oak_PBR}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("./models3/Drawing.gltf");
