/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\public\models\h_stairs.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function H_stairs(props) {
  const { nodes, materials } = useGLTF('./models/h_stairs.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2083.geometry} material={materials['24_pool_water_texture_seamless']} position={[24.818, 1.774, -15.869]} />
      <mesh geometry={nodes.Material3006.geometry} material={materials.Fan_Palm_leaf} position={[25.77, 2.202, -16.045]} />
      <mesh geometry={nodes.Material2037.geometry} material={materials.Polished_Concrete_Old} position={[25.483, 1.821, -15.491]} />
      <mesh geometry={nodes.Material2253.geometry} material={materials.Color_F19} position={[24.131, 2.083, -15.88]} />
    </group>
  )
}

useGLTF.preload('./models/h_stairs.gltf')
