/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\public\models\k_common.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function K_common(props) {
  const { nodes, materials } = useGLTF('./models/k_common.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[20.104, 2.204, -20.289]}>
        <mesh geometry={nodes.Material2190.geometry} material={materials.sehpa_mermer__marble} />
        <mesh geometry={nodes.Material2190_1.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Material2190_2.geometry} material={materials['23_brushed_dark_steel_metal']} />
        <mesh geometry={nodes.Material2190_3.geometry} material={materials['16_Terrazzo_surface_PBR_texture-seamless']} />
        <mesh geometry={nodes.Material2190_4.geometry} material={materials.material} />
      </group>
      <group position={[20.48, 2.695, -21.879]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021}>
        <mesh geometry={nodes.Material2357.geometry} material={materials['16_Terrazzo_surface_PBR_texture-seamless.001']} />
        <mesh geometry={nodes.Material2357_1.geometry} material={materials['material.001']} />
        <mesh geometry={nodes.Material2357_2.geometry} material={materials['Translucent_Glass_Gray.001']} />
        <mesh geometry={nodes.Material2357_3.geometry} material={materials['23_brushed_dark_steel_metal.001']} />
        <mesh geometry={nodes.Material2357_4.geometry} material={materials['31_brushed_copper_metal_texture-seamless.001']} />
        <mesh geometry={nodes.Material2357_5.geometry} material={materials['brushed_aluminium.001']} />
        <mesh geometry={nodes.Material2357_6.geometry} material={materials['31_brushed_copper_metal_texture-seamless_6.001']} />
        <mesh geometry={nodes.Material2357_7.geometry} material={materials['sehpa_mermer__marble.001']} />
        <mesh geometry={nodes.Material2357_8.geometry} material={materials['material_12.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/k_common.gltf')
