/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\kitchen_1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from "../../../constants/Customization";

export function Kitchen_1(props) {
  const { nodes, materials } = useGLTF('./models3//kitchen_1.gltf')
	const { codeOBJ, loc, setLoc } = useCustomization();

  return (
    <group {...props} dispose={null}>
      <group position={[20.104, 2.204, -20.289]}>
        <mesh geometry={nodes.Material2190.geometry} material={materials.sehpa_mermer__marble} />
        <mesh geometry={nodes.Material2190_1.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Material2190_2.geometry} material={materials['23_brushed_dark_steel_metal']} />
        <mesh geometry={nodes.Material2190_3.geometry} material={materials['16_Terrazzo_surface_PBR_texture-seamless']} />
        <mesh geometry={nodes.Material2190_4.geometry} material={materials.material} />
      </group>
      <group position={[20.138, 2.148, -18.28]} visible={codeOBJ["ktChair"] === 1}>
        <mesh geometry={nodes.Material2187.geometry} material={materials['23_brushed_dark_steel_metal']} />
        <mesh geometry={nodes.Material2187_1.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Material2187_2.geometry} material={materials['31_brushed_copper_metal_texture-seamless']} />
        <mesh geometry={nodes.Material2187_3.geometry} material={materials.material} />
      </group>
      <mesh geometry={nodes['k-Chair-B'].geometry} material={materials.Lamed_chair} position={[20.154, 2.234, -18.25]} visible={codeOBJ["ktChair"] === 0}/>
      <group position={[20.09, 2.827, -19.883]} visible={codeOBJ["ktTaps"] === 0}>
        <mesh geometry={nodes.pipa4_material_2_0001.geometry} material={materials['metal.001']} />
        <mesh geometry={nodes.pipa4_material_2_0001_1.geometry} material={materials['rubber.001']} />
      </group>
      <mesh geometry={nodes['k-Tap002'].geometry} material={materials['metal.001']} position={[20.072, 2.711, -19.861]} visible={codeOBJ["ktTaps"] === 2}/>
      <mesh geometry={nodes['k-Tap003'].geometry} material={materials['metal.001']} position={[20.063, 2.702, -19.841]} visible={codeOBJ["ktTaps"] === 3}/>
      <group position={[20.084, 2.672, -19.85]} visible={codeOBJ["ktTaps"] === 5}>
        <mesh geometry={nodes.pipa7_material3_0001.geometry} material={materials['metal.001']} />
        <mesh geometry={nodes.pipa7_material3_0001_1.geometry} material={materials['rubber.001']} />
      </group>
      <mesh geometry={nodes['k-Tap004'].geometry} material={materials['metal.001']} position={[20.073, 2.701, -19.87]} visible={codeOBJ["ktTaps"] === 4}/>
      <mesh geometry={nodes['k-Tap006'].geometry} material={materials['metal.001']} position={[20.089, 2.688, -19.888]} visible={codeOBJ["ktTaps"] === 6}/>
      <mesh geometry={nodes['k-Tap001'].geometry} material={materials['metal.001']} position={[20.099, 2.744, -19.866]} visible={codeOBJ["ktTaps"] === 1}/>
      <group position={[20.111, 3.556, -19.587]} visible={codeOBJ["ktLamp"] === 1}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Car plastic dark']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.Steel} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials.Glass} />
      </group>
      <group position={[20.094, 3.491, -19.588]} visible={codeOBJ["ktLamp"] === 2}>
        <mesh geometry={nodes.Mesh154.geometry} material={materials['tepa.001']} />
        <mesh geometry={nodes.Mesh154_1.geometry} material={materials['xlor up.001']} />
        <mesh geometry={nodes.Mesh154_2.geometry} material={materials['lampa.001']} />
        <mesh geometry={nodes.Mesh154_3.geometry} material={materials['xrom.001']} />
        <mesh geometry={nodes.Mesh154_4.geometry} material={materials['Material #29.001']} />
        <mesh geometry={nodes.Mesh154_5.geometry} material={materials['Material #30.001']} />
        <mesh geometry={nodes.Mesh154_6.geometry} material={materials['simi.001']} />
        <mesh geometry={nodes.Mesh154_7.geometry} material={materials['01 wood.001']} />
        <mesh geometry={nodes.Mesh154_8.geometry} material={materials['01.001']} />
        <mesh geometry={nodes.Mesh154_9.geometry} material={materials['02 wood.001']} />
        <mesh geometry={nodes.Mesh154_10.geometry} material={materials['02.001']} />
        <mesh geometry={nodes.Mesh154_11.geometry} material={materials['03 wood.001']} />
        <mesh geometry={nodes.Mesh154_12.geometry} material={materials['03.001']} />
      </group>
      <group position={[20.785, 3.483, -19.59]} visible={codeOBJ["ktLamp"] === 0}>
        <mesh geometry={nodes.Material2192.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Material2192_1.geometry} material={materials['26_old_dirty_copper_metal_texture-seamless']} />
        <mesh geometry={nodes.Material2192_2.geometry} material={materials.Color_M07} />
      </group>
    </group>
  )
}

useGLTF.preload('./models3//kitchen_1.gltf')
