/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\Dinning_part2.gltf 
*/

import React, { useRef } from 'react'
import { useLoader  } from "@react-three/fiber";
import { useCustomization } from "../../../constants/Customization";
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function Dinning(props) {
	const { codeOBJ, loc, setLoc } = useCustomization();
  // const k_table_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_table/k_table_a.glb')
  // const k_table_b = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_table/k_table_b.glb')
 
  // const k_lamp_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_lamp/k_lamp_a.glb')
  // const k_lamp_b = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_lamp/k_lamp_b.glb')
  // const k_lamp_c = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_lamp/k_lamp_c.glb')
  // const k_lamp_d = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_lamp/k_lamp_d.glb')
  // const k_lamp_e = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_lamp/k_lamp_e.glb')
  
  // const k_tap_a = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_a.glb')
  // const k_tap_b = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_b.glb')
  // const k_tap_c = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_c.glb')
  // const k_tap_d = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_d.glb')
  // const k_tap_e = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_e.glb')
  // const k_tap_f = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_f.glb')
  // const k_tap_g = useLoader(GLTFLoader, 'https://www.backend.visualizenbuild.com/static/k_tap/k_tap_g.glb')
  
  return (
    <>
      {/* <primitive object={d_table_a.scene} /> */}
      {/* <primitive object={dn_table_a.scene} />
      <primitive object={dn_table_b.scene} /> */}
      
    </>
  )
}


