/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models3\Dinning_part2.gltf 
*/

import React, { useRef } from 'react'
import { useLoader  } from "@react-three/fiber";
import { useCustomization } from "../../../constants/Customization";
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function MainBuilding(props) {
	const { codeOBJ, loc, setLoc } = useCustomization();
  const mainBuilding = useLoader(GLTFLoader, './public/models/mainBuilding.gltf')


  return (
    <>
      <primitive object={mainBuilding.scene} />
    </>
  )
}


